# Use powerline
USE_POWERLINE="true"
# Source manjaro-zsh-configuration
if [[ -e /usr/share/zsh/manjaro-zsh-config ]]; then
  source /usr/share/zsh/manjaro-zsh-config
fi
# Use manjaro zsh prompt
if [[ -e /usr/share/zsh/manjaro-zsh-prompt ]]; then
  source /usr/share/zsh/manjaro-zsh-prompt
fi

## Aliases
alias seco='/usr/local/SecoClient/serviceclient/SecoClientCS && notify-send --urgency=critical -a Secoclient -i /usr/local/SecoClient/image/ICON.ico  "Fin de la conexion"'
alias seco_start='/usr/local/SecoClient/promote/SecoClientPromoteService'
source /usr/share/nvm/init-nvm.sh
